### ISSUE TITLE
UnicodeDecodeError: 'utf8' codec can't decode byte 0xf4 in position 13: invalid continuation byte

### ISSUE THREAD

**Issue by lmaroncelli** [SublimeText/CTags#194]
Hi all,
when I try to rebuild tags I get this error in console 

```
Exception in thread Thread-25:
Traceback (most recent call last):
  File ".\threading.py", line 532, in __bootstrap_inner
  File ".\threading.py", line 484, in run
  File "./ctagsplugin.py", line 118, in run
    result = func(*args, **kwargs)
  File "./ctagsplugin.py", line 862, in build_ctags
    recursive=recursive, cmd=command)
  File "./ctags.py", line 315, in build_ctags
    resort_ctags(tag_file)
  File "./ctags.py", line 348, in resort_ctags
    for line in fh:
  File ".\codecs.py", line 679, in next
  File ".\codecs.py", line 610, in next
  File ".\codecs.py", line 525, in readline
  File ".\codecs.py", line 472, in read
UnicodeDecodeError: 'utf8' codec can't decode byte 0xf4 in position 13: invalid continuation byte
```

**Comment by GW520** [comment]
弄way
