### ISSUE TITLE
Valid MySQL escape characters likely to cause 'IndexError: list index out of range'

### ISSUE THREAD

**Issue by Kludgy** [SublimeText/CTags#278]
```
Building CTags for D:\broken.sql: Please be patient
error: An unknown error occured.
Check the console for info.
Exception in thread Thread-454:
Traceback (most recent call last):
  File "./threading.py", line 901, in _bootstrap_inner
  File "./threading.py", line 858, in run
  File "ctagsplugin in C:\Users\user\AppData\Roaming\Sublime Text 3\Installed Packages\CTags.sublime-package", line 119, in run
  File "ctagsplugin in C:\Users\user\AppData\Roaming\Sublime Text 3\Installed Packages\CTags.sublime-package", line 907, in build_ctags
  File "ctagsplugin in C:\Users\user\AppData\Roaming\Sublime Text 3\Installed Packages\CTags.sublime-package", line 892, in build_ctags
  File "ctags in C:\Users\user\AppData\Roaming\Sublime Text 3\Installed Packages\CTags.sublime-package", line 331, in build_ctags
  File "ctags in C:\Users\user\AppData\Roaming\Sublime Text 3\Installed Packages\CTags.sublime-package", line 365, in resort_ctags
IndexError: list index out of range
```

Environment:
- Windows
- `ctags58.exe`
- Sublime Text 3 - Stable Build 3065

Minimal repro case:

``` sql
INSERT INTO X (a) VALUES ('\'');
INSERT INTO X (a) VALUES ('DOMAIN');
INSERT INTO X (a) VALUES ('');
```
- DOMAIN is a valid SQL token that happened to be in the original file as a string value.
- Other SQL tokens I've tried don't lead to this issue.
- Theory: Incorrect handling of backlash escape sequences.

I'll do debugging against head when I have time, unless someone beats me to it. ;)

**Comment by Kludgy** [comment]
`ctags58.exe` produces some trailing garbage `);` in the tags file for the repro case above. This looks more like an `exuberant-ctags` bug.

However, should Sublime CTags try to work around the issue in the meantime?

**Comment by Kludgy** [comment]
Related PR: https://github.com/SublimeText/CTags/pull/279
