### ISSUE TITLE
Error when creating tag files

### ISSUE THREAD

**Issue by northern55boy** [SublimeText/CTags#292]
Hi:

I am seeing the following error when trying to generate (large) tag files for my project. 

```
error: An unknown error occured.
Check the console for info.
Exception in thread Thread-6:
Traceback (most recent call last):
  File "./threading.py", line 901, in _bootstrap_inner
  File "./threading.py", line 858, in run
  File "ctagsplugin in /home/robert/.config/sublime-text-3/Installed Packages/CTags.sublime-package", line 119, in run
  File "ctagsplugin in /home/robert/.config/sublime-text-3/Installed Packages/CTags.sublime-package", line 907, in build_ctags
  File "ctagsplugin in /home/robert/.config/sublime-text-3/Installed Packages/CTags.sublime-package", line 892, in build_ctags
  File "ctags in /home/robert/.config/sublime-text-3/Installed Packages/CTags.sublime-package", line 331, in build_ctags
  File "ctags in /home/robert/.config/sublime-text-3/Installed Packages/CTags.sublime-package", line 365, in resort_ctags
IndexError: list index out of range
```

The tag file generated is quite large, ~134M, but for the most part, I can still use it for jumping to definitions from within sublime. I am using sublime 3 (build 3083) and Ctags v0.3.9 running on Ubuntu 14.04. I see that there was a similar issue raised (#145) for an almost identical problem, but specific to the 'sorting' of the tag file. I was wondering if specifying the 'sort' option ever made it into a released branch so that I might try it.

Regards,
Robert

**Comment by stephenfin** [comment]
This is the same issue as #282. I've been meaning to figure this out, but just haven't got around to it :disappointed:. Hopefully the weather will take a turn for the worst and I'll have time to kill some weekend soon!

As for the sort option, I never bothered releasing it as I wasn't happy with the performance and there wasn't enough demand for it. If you're interested in reviving it then by all means feel free (it should be on a branch around here).

**Comment by sublimator** [comment]
This plugin still used even with ST3  builtin indexing?

**Comment by stephenfin** [comment]
I don't use it much any more myself

**Comment by northern55boy** [comment]
Stephen, thanks for the reply.
Good point about that built-in indexing with Sublime 3. I was just using 
someone elses 'canned recipe' for setting up a development environment 
with Sublime. I'll see if it (built-in) will meet my needs.

Regards,
Robert
