### ISSUE TITLE
Can't find any relevant tags file

### ISSUE THREAD

**Issue by dody** [SublimeText/CTags#308]
This morning i rebuilt my ctags file and since then plugin is telling me "Can't find any relevant tags file".
I tough there is something wrong with tag file but it looks fine and I was despered enought to open the CTAGS python code and did some debug.

I have tags stored in one file. Ctags setings in file CTags.sublime-settings are:

```
{
	"extra_tag_files": [".gemtags", "tags","h:\\confidential\\cscope\\tags" ]
}
```
I have put some debug prints found out that function get_alternate_tags_paths responsible to find tags in extra files did not run at all.

I would appreciate any help or advice. Thank you.

I am using sublime 2

**Comment by dody** [comment]
I believe my problem might be related to instaling python 3 the day before my problem occured.

I see some errors in console when sublime starts:


```
Reloading plugin C:\Users\jkoczman\AppData\Roaming\Sublime Text 2\Packages\CTags\test_ctags.py
Traceback (most recent call last):
  File ".\sublime_plugin.py", line 62, in reload_plugin
  File ".\test_ctags.py", line 14, in <module>
    import unittest2 as unittest
ImportError: No module named unittest2
Reloading plugin C:\Users\jkoczman\AppData\Roaming\Sublime Text 2\Packages\CTags\test_ctagsplugin.py
Traceback (most recent call last):
  File ".\sublime_plugin.py", line 62, in reload_plugin
  File ".\test_ctagsplugin.py", line 13, in <module>
    import unittest2 as unittest
ImportError: No module named unittest2
```

**Comment by dody** [comment]
I have managed to get rid of errors from previous post by upgrading from sublime 2 to sublime 3.

However Ctags are still not working.

**Comment by dody** [comment]
Heureka!

Long story short: Option extra_tag_files seem not to work at all for me and I had to put ".tags" files inside my project.

Looks like you cannot have .tags file in separate folder for example
C:\project
C:\tags\my_fag_file

Please can someone explain me how to achieve CTags plugin to work with my desired folder structure since it is standard in our company?

**Comment by biemster** [comment]
I'm having the same issue with "extra_tag_files" but I just started 5 minutes ago with this plugin. I had to change "tag_file" to "tags" (without dot) to find my tags file, while this is already in the "extra_tag_files" field by default.

Is the extra_tag_files not working at the moment or do I not understand it properly (Making it a documentation issue maybe)?

**Comment by biemster** [comment]
Looking at the code it seems to completely disregard the extra_tag_files in get_alternate_tags_paths() when the "(tags_file)_search_paths" file is not found. I've done a quick hack to make it work in my use case, but I'm not sure if it will break others. I could make a pull request if more people run in this issue.

**Comment by dody** [comment]
Could you please share your fix?

I did dirty fix with setting "tag_file" : "cscope\\.tags"

**Comment by biemster** [comment]
Your dirty fix is a lot cleaner than mine :). I just removed
`ctagsplugin.py:241 "if os.path.exists(tags_paths):"`
so it always uses the locations given in extra_tag_files.

**Comment by shakeelmohamed** [comment]
I had to explicitly set `"tag_file" : "tags"` in my `CTags.sublime-settings`, the `extra_tag_files` setting appears to have no effect
