### ISSUE TITLE
'IndexError: list index out of range' when trying to build tags for the nodejs/node repo

### ISSUE THREAD

**Issue by shakeelmohamed** [SublimeText/CTags#329]
If I had to guess this could be related to there being too many symbols in the the repo 😄 

```
Building CTags for /Users/<snip>/node: Please be patient
error: An unknown error occured.
Check the console for info.
Exception in thread Thread-163:
Traceback (most recent call last):
  File "./python3.3/threading.py", line 901, in _bootstrap_inner
  File "./python3.3/threading.py", line 858, in run
  File "ctagsplugin in /Users/<snip>/Library/Application Support/Sublime Text 3/Installed Packages/CTags.sublime-package", line 92, in run
  File "ctagsplugin in /Users/<snip>/Library/Application Support/Sublime Text 3/Installed Packages/CTags.sublime-package", line 891, in build_ctags
  File "ctagsplugin in /Users/<snip>/Library/Application Support/Sublime Text 3/Installed Packages/CTags.sublime-package", line 874, in build_ctags
  File "/Users/<snip>/sublime/Installed Packages/CTags.sublime-package/ctags.py", line 326, in build_ctags
    resort_ctags(tag_file)
  File "/Users/<snip>/sublime/Installed Packages/CTags.sublime-package/ctags.py", line 360, in resort_ctags
    keys.setdefault(line.split('\t')[FILENAME], []).append(line)
IndexError: list index out of range
```

**Comment by saenom** [comment]
I have the same problem

**Comment by shakeelmohamed** [comment]
I'm seeing this on another repo now while trying to rebuild tags.

**Comment by stevenchanin** [comment]
+1

**Comment by drewish** [comment]
Also running into this with ruby code. Works fine in other, smaller apps I work on though.

**Comment by drewish** [comment]
https://github.com/SublimeText/CTags/pull/279 fixed this issue for me.

**Comment by drewish** [comment]
Hey, glad to see someone is maintaining this again! Thank you!
